# Generated by Django 4.2 on 2023-04-25 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_authority'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='authority',
            new_name='zarinpal_authority',
        ),
    ]
